[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.124.1"
NODE_VERSION = "20"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
from = "/docs/tokens/"
to = "/docs/configuration/tokens/"
status = 301
force = false

[[redirects]]
from = "/docs/storage/"
to = "/docs/configuration/storage/"
status = 301
force = false

[[redirects]]
from = "/docs/oauth2/"
to = "/docs/configuration/oauth2/"
status = 301
force = false

[[redirects]]
from = "/docs/api/"
to = "/docs/configuration/api/"
status = 301
force = false

[[redirects]]
from = "/docs/custom-scopes-claims-clients/"
to = "/docs/configuration/custom-scopes-claims-clients/"
status = 301
force = false

[[redirects]]
from = "/docs/templates/"
to = "/docs/guides/templates/"
status = 301
force = false

[[redirects]]
from = "/docs/token-exchange/"
to = "/docs/guides/token-exchange/"
status = 301
force = false

[[redirects]]
from = "/docs/using-dex/"
to = "/docs/guides/using-dex/"
status = 301
force = false

[[redirects]]
from = "/docs/kubernetes/"
to = "/docs/guides/kubernetes/"
status = 301
force = false

[[redirects]]
from = "/docs/kubelogin-activedirectory/"
to = "/docs/guides/kubelogin-activedirectory/"
status = 301
force = false
